# Generated by Django 5.2.5 on 2025-10-27 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Región')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True, verbose_name='RUT / NIF')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Fantasía')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('pais', models.CharField(default='Chile', max_length=64)),
                ('condiciones_pago', models.CharField(default='Contado', max_length=50, verbose_name='Condiciones de Pago')),
                ('moneda', models.CharField(default='CLP', max_length=8)),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='proveedores.region')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lead_time_dias', models.PositiveIntegerField(default=7)),
                ('min_lote', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preferente', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Producto por Proveedor',
                'verbose_name_plural': 'Productos por Proveedor',
                'db_table': 'proveedor_producto',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
    ]
