# Generated by Django 5.2.5 on 2025-11-27 01:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('OPER_COMPRAS', 'Operador de Compras'), ('OPER_INVENTARIO', 'Operador de Inventario'), ('OPER_PRODUCCION', 'Operador de Producción'), ('OPER_VENTAS', 'Operador de Ventas'), ('ANALISTA_FIN', 'Analista Financiero'), ('AUDITOR', 'Auditor'), ('USUARIO', 'Usuario General')], default='USUARIO', max_length=20, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('mfa_habilitado', models.BooleanField(default=False, verbose_name='MFA Habilitado')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('sesiones_activas', models.PositiveIntegerField(default=0, verbose_name='Sesiones Activas')),
                ('area', models.CharField(blank=True, choices=[('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('INVENTARIO', 'Inventario'), ('PRODUCCION', 'Producción'), ('FINANZAS', 'Finanzas'), ('ADMINISTRACION', 'Administración'), ('GERENCIA', 'Gerencia General'), ('RRHH', 'Recursos Humanos')], max_length=30, null=True, verbose_name='Área/Unidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('requiere_cambio_password', models.BooleanField(default=False, verbose_name='Requiere cambio de contraseña')),
                ('intentos_fallidos', models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_grupo', related_query_name='usuario', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_permiso', related_query_name='usuario', to='auth.permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
