# Generated by Django 5.2.5 on 2025-11-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_lilis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
    ]
